### ISSUE TITLE
what does true or false mean?

### ISSUE THREAD

**Issue by gh0st4s** [rcamino/honeypot-detection#1]
Excuse me, what does the positive column marked as "False" in /honeybadger_labels/HoneyBadger Evaluation-Straw Man Contract.csv mean? Does it mean that the smart contract is not a honeypot ? Or does it mean the detection system cannot detect that honeypot?
Thank you for help.

**Comment by rcamino** [comment]
Hi,

Every contract listed on each csv file was classified as honeypot by the [HoneyBadger](https://github.com/christoftorres/HoneyBadger) tool.
Then they were manually inspected by the HoneyBadger authors, and marked as Positive=TRUE when they were actual honeypots, and Positive=FALSE otherwise.
The contracts with Positive=TRUE were labeled as honeypots for this study, and both the Positive=FALSE and the contracts not in any list (from the first 6.5M blocks) were labeled as non-honeypots.

Best,
Ramiro.
